### ISSUE TITLE
xchain-thorchain getTransactions issues

### ISSUE THREAD

**Issue by cryptotester** [xchainjs/xchainjs-lib#584]
Module: **xchain-thorchain**

Version: 0.24.1 (latst version)

Method with issues: `getTransactions`

Docu: http://docs.xchainjs.org/xchain-client/xchain-thorchain/available-functions/client.html#gettransactions

**Issue 1:**

startTime is ignored.

See, the standard parameters to pass when calling getTransactions:
```
export declare type TxHistoryParams = {
    address: Address;
    offset?: number;
    limit?: number;
    startTime?: Date;
    asset?: string;
};
```

However, in the implementation (`node_modules/@xchainjs/xchain-thorchain/lib/index.js`), startTime is ignored. I see, instead:

```
            const txMinHeight = undefined;
            const txMaxHeight = undefined;
```

These 2 seems the parameters I'm looking for, but they are not very convenient... how can I know what height at a specific startTime? 

Expected result: I think, given a startTime (Date in UTC), the implementation should convert (internally) the startTime to txMinHeight so to have a standard API between chains which works in a similar way...

**Issue 2:**

I leave txMinHeight and txMaxHeight blank. I get the latest 10 (or the amout I define in `limit`) transactions, **but not the ones I did Today.**

Expected result: if I specify no filter, I should get in the latest 10 transactions on Thorchain also the ones I did Today.

**Comment by hippocampus-web3** [comment]
The issue at hand is the lack of an efficient mechanism to convert timestamps into block numbers, which is why this feature is currently unsupported for CosmosSDK blockchains.

As a workaround, I propose defining a basic type for transaction history parameters:

```typescript
export type TxHistoryParams = {
  address: Address;
  offset?: number;
  limit?: number;
  asset?: string;
};

```
Then, we can introduce two extended types:

```typescript
type TxHistoryParamsWithTime = TxHistoryParams & {
  startTime: boolean;
};
```

```typescript
type TxHistoryParamsWithBlock = TxHistoryParams & {
  startBlock: boolean;
};
```

Although this isn't an ideal solution, it could eliminate confusion for library users by explicitly stating that filtering by startTime is unsupported for certain blockchains. What are your thoughts on this, @Thorian1te ? Any other ideas?
