### ISSUE TITLE
bug: estimate swap incorrect calculation

### ISSUE THREAD

**Issue by mikewyszinski** [xchainjs/xchainjs-lib#708]
from discord: https://discord.com/channels/838986635756044328/842252939149967382/1058063440616374372

the calculation of "outboundFee" for eth (thor.rune -> eth.eth) is somehow too small (for example, it returns 0.00048, although it should be 0.0048), apparently one more "decimal" is missing somewhere.

**Comment by Thorian1te** [comment]
hmm not sure if this is an issue, in inbound_addresses its stated to be Gwei at 480000 which works out to be eth amount 0.00048, see https://www.alchemy.com/gwei-calculator,

**Comment by CodeFunta** [comment]
Hi, I would like to suggest to change this line (https://github.com/xchainjs/xchainjs-lib/blob/b1fcdc50ccb1bf5031991aeb7619e273825e0694/packages/xchain-thorchain-query/src/thorchain-query.ts#L232) to this line: `let outboundFeeInOutboundGasAsset = calcNetworkFee(params.destinationAsset, destinationInboundDetails).times(3);`.

**Why:**
* According to description in https://dev.thorchain.org/thorchain-dev/concepts/fees#outbound-fee the outboundFee = txSize* gasRate * 3
* It's more relevant with https://thornode.ninerealms.com/thorchain/quote/swap endpoint output
*  My test transactions in mainnet with BTC->USDT swap has always refunded since limit value is always greater than real output value after all outbound fees

**Comment by CodeFunta** [comment]
plus I think that we don't need to substract inbound fee from not chain asset, ie. if we swapping USDT to BTC this fee must be included only with native chain asset (eth, btc, avax, etc) and netoutput and affiliate fee will be more relevant.
so we can transform this line https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-thorchain-query/src/thorchain-query.ts#L253  into following code: 
`const inputMinusInboundFeeInAsset = isChainAsset(input.asset) ? input.minus(inboundFeeInInboundAsset) : input;`

+ add method isChainAsset helper into utils/swap or thorchain-query:
`export const isChainAsset = (asset: Asset): boolean => eqAsset(asset, getChainAsset(asset.chain));`

What do you think?

**Comment by GrassRootsCrypto** [comment]
Lets break down the second comment. 

First, swapping USDT to BTC. 
You need to account for the inbound tx cost when giving the quote. So need to find the ETH tx cost and subtract it away from the USDT amount sent in before you remove the rest of the fees. This will be higher than an ether cost as ERC20 transfers are bigger - contract call.

isChainAsset could work and clean things up a bit, will have to look into that more later. 

To the last point, there is always an inbound tx cost to any asset, so you couldn't have inboundFee = 0.

**Comment by CodeFunta** [comment]
> Lets break down the second comment.
> 
> First, swapping USDT to BTC. You need to account for the inbound tx cost when giving the quote. So need to find the ETH tx cost and subtract it away from the USDT amount sent in before you remove the rest of the fees. This will be higher than an ether cost as ERC20 transfers are bigger - contract call.
> 
> isChainAsset could work and clean things up a bit, will have to look into that more later.
> 
> To the last point, there is always an inbound tx cost to any asset, so you couldn't have inboundFee = 0.

Hi @GrassRootsCrypto, thank you for your comments.
Regarding the last point about inbound tx cost, of course inboundFee can't be zero, but we don't need to substract it from input token amount in case of not chain asset since it will skew the real net output and affiliate fee calculation, plus check in covering fee. 

So when I as developer calling the estimate method for USDT->BTC I want to receive results as following:
* inbound fee in source network chain asset (ETH)
* oubound fee in target network chain asset (BTC)
* netoutput in target  asset (BTC)

PS: I think that substracting inbound fee in ETH converted to BTC is wrong and will skew real output results

**Comment by GrassRootsCrypto** [comment]
@CodeFunta, thanks for the reply. 
I now see it. 
When sending 30 USDT, gas is paid in Ether directly from the user's wallet and not taken from the 30 USDT. So inbound fee will be 0 however the user will be paying about $33.43 overall (30 USDT + Gas). The user should be made aware of the gas requirements though when the quote returns.

**Comment by CodeFunta** [comment]
> @CodeFunta, thanks for the reply. I now see it. When sending 30 USDT, gas is paid in Ether directly from the user's wallet and not taken from the 30 USDT. So inbound fee will be 0 however the user will be paying about $33.43 overall (30 USDT + Gas). The user should be made aware of the gas requirements though when the quote returns.

Hi @GrassRootsCrypto , yes and I as developer taking inbound fee , outbound fee and netoutput with UI so user is aware for totals fee and estimated output value in destination token
