### ISSUE TITLE
FIX: Binance PK derivation path 

### ISSUE THREAD

**Issue by Thorian1te** [xchainjs/xchainjs-lib#931]
Current PK derivation path in chain-binance is "44'/931'/0'/0/".
 
 
BNB is not correct (needs to change to 714)
 
Other libraries define this path for Binance Chain as "44'/714'/0'/0/".
😬 
......
- [ ] Change path 
- [ ] Allow for legacy paths to remain (so funds are not lost)

......

**Comment by Thorian1te** [comment]
Im not sure about this one. 
yes its an issue, but are we already too far in ? how many front ends are supporting the first config
-> xchain-binance is "44'/931'/0'/0/"

**Comment by 0xp3gasus** [comment]
It is a problem because the BIP44 BNB cointype is 714, but in fact the xchainjs-lib derivation path is not being used for the BNB client. From the xchainjs side, private keys are being generated with the bnb library using only the index. The `crypto.getPrivateKeyFromMnemonic` uses  the official derivation path internally
